/**
 * Form-specific PDF generation utilities
 * Extends the existing PDF generation capabilities for forms
 */

/**
 * Generate PDF markup for a form (reused for both vector and raster PDFs)
 * @param {object} formData - The form data to display
 * @param {object} schema - The form schema (for labels and structure)
 * @returns {string} HTML markup for the form
 */
export function buildFormPdfMarkup(formData, schema = {}) {
  const formFields = Object.keys(schema.shape || {});

  // If no schema provided, just show all form data
  const fieldsToShow = formFields.length > 0 ? formFields : Object.keys(formData);

  const fieldsHtml = fieldsToShow.map(fieldName => {
    const value = formData[fieldName];
    const label = schema.shape[fieldName]?._def?.description ||
                  fieldName.replace(/([A-Z])/g, ' $1').replace(/^./, str => str.toUpperCase());

    // Format the value is null or undefined, show placeholder
    const displayValue = value === null || value === undefined
      ? '(Not provided)'
      : Array.isArray(value)
        ? value.join(', ')
        : String(value);

    return `
      <div class="form-field-row">
        <div class="form-field-label">${escapeHtml(label)}:</div>
        <div class="form-field-value">${escapeHtml(displayValue)}</div>
      </div>
    `;
  }).join('');

  return `
    <!DOCTYPE html>
    <html lang="en">
    <head>
      <meta charset="utf-8"/>
      <meta name="viewport" content="width=device-width, initial-scale=1"/>
      <title>Form Submission - Creative Companion</title>
      <link rel="preconnect" href="https://fonts.googleapis.com"/>
      <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
      <link href="https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@400;500;600;700&display=swap" rel="stylesheet"/>
      <style>
        :root { color-scheme: light; }
        * { box-sizing: border-box; }
        body {
          margin: 0;
          font-family: "Plus Jakarta Sans", system-ui, -apple-system, sans-serif;
          color: #0B1220;
          background: #EEF0F6;
          line-height: 1.5;
          -webkit-font-smoothing: antialiased;
        }
        .form-container { max-width: 600px; margin: 0 auto; padding: 2rem; }
        .form-header {
          text-align: center;
          margin-bottom: 2rem;
          padding-bottom: 1rem;
          border-bottom: 1px solid rgba(11,18,32,.08);
        }
        .form-title {
          font-size: 1.5rem;
          font-weight: 600;
          color: #1C1917;
          margin-bottom: 0.5rem;
        }
        .form-subtitle {
          font-size: 0.9rem;
          color: rgba(11,18,32,.65);
        }
        .form-fields { margin-bottom: 2rem; }
        .form-field-row {
          display: grid;
          grid-template-columns: 1fr 1fr;
          gap: 1rem 2rem;
          margin-bottom: 1.25rem;
          page-break-inside: avoid;
        }
        .form-field-label {
          font-weight: 600;
          color: #0B1220;
        }
        .form-field-value {
          color: rgba(11,18,32,.65);
          word-break: break-word;
        }
        .form-footer {
          margin-top: 2rem;
          padding-top: 1rem;
          border-top: 1px solid rgba(11,18,32,.08);
          font-size: 0.8rem;
          color: rgba(11,18,32,.45);
          text-align: center;
        }
        @media print {
          body { background: #fff; }
          .form-container { padding: 0; }
        }
      </style>
    </head>
    <body>
      <div class="form-container">
        <div class="form-header">
          <h1 class="form-title">Form Submission</h1>
          <p class="form-subtitle">Creative Companion · ${new Date().toLocaleDateString()}</p>
        </div>
        <div class="form-fields">
          ${fieldsHtml}
        </div>
        <div class="form-footer">
          Generated by Creative Companion · Form data export
        </div>
      </div>
    </body>
    </html>
  `;
}

/**
 * Escape HTML special characters to prevent XSS
 * @param {string} text - Text to escape
 * @returns {string} Escaped text
 */
function escapeHtml(text) {
  if (!text) return '';
  return String(text)
    .replace(/&/g, '&')
    .replace(/</g, '<')
    .replace(/>/g, '>')
    .replace(/"/g, '"')
    .replace(/'/g, '&#039;');
}

/**
 * Download form as PDF (vector-based)
 * @param {object} formData - The form data to include in PDF
 * @param {object} schema - The form schema (for labels and structure)
 * @param {Promise|null} handlePromise - From captureSaveHandle()
 * @param {{ hideWatermark?: boolean }} [options]
 * @returns {Promise<{ ok: boolean, error?: string, cancelled?: boolean, method?: string }>}
 */
export async function downloadFormPdf(
  formData,
  schema = {},
  handlePromise = null,
  options = {}
) {
  try {
    await preloadPdfEngine()
    const { jsPDF } = await jsPdfModulePromise

    const pdf = new jsPDF({
      unit: 'pt',
      format: 'letter',
      compress: true,
    })

    const margin = 50
    const pageW = pdf.internal.pageSize.getWidth()
    const pageH = pdf.internal.pageSize.getHeight()
    const contentW = pageW - margin * 2

    let y = margin

    // Add header
    pdf.setFont('helvetica', 'bold')
    pdf.setFontSize(18)
    pdf.setTextColor(28, 25, 23) // Dark gray from your palette
    pdf.text('Form Submission', margin, y)
    y += 30

    pdf.setFont('helvetica', 'normal')
    pdf.setFontSize(10)
    pdf.setTextColor(11, 18, 32) // Blue-gray
    pdf.text(`Creative Companion · ${new Date().toLocaleDateString()}`, margin, y)
    y += 40

    // Add form fields
    pdf.setFont('helvetica', 'bold')
    pdf.setFontSize(12)
    pdf.setTextColor(28, 25, 23)

    const formFields = Object.keys(schema.shape || {});
    const fieldsToShow = formFields.length > 0 ? formFields : Object.keys(formData);

    for (const fieldName of fieldsToShow) {
      const value = formData[fieldName];
      const label = schema.shape[fieldName]?._def?.description ||
                    fieldName.replace(/([A-Z])/g, ' $1').replace(/^./, str => str.toUpperCase());
      const displayValue = value === null || value === undefined
        ? '(Not provided)'
        : Array.isArray(value)
          ? value.join(', ')
          : String(value);

      // Check if we need a new page
      if (y > pageH - margin - 60) {
        pdf.addPage()
        y = margin
      }

      // Draw label
      pdf.text(`${label}:`, margin, y)

      // Draw value (wrapping if needed)
      pdf.setFont('helvetica', 'normal')
      const valueLines = pdf.splitTextToSize(displayValue, contentW - 100)
      pdf.text(valueLines, margin + 150, y)

      // Move y position based on number of lines
      const lineHeight = 12 * LINE_HEIGHT.normal // 12pt font * 1.5 line height
      y += Math.max(valueLines.length, 1) * lineHeight + 10
    }

    // Add footer
    if (y > pageH - margin - 30) {
      pdf.addPage()
      y = margin
    }

    pdf.setFont('helvetica', 'normal')
    pdf.setFontSize(8)
    pdf.setTextColor(150, 150, 150)
    pdf.text(`Generated by Creative Companion · Form data export`, margin, pageH - margin)

    const slug = 'form-submission'
    const name = `${slug}-form.pdf`

    let blob
    try {
      const ab = pdf.output('arraybuffer')
      blob = new Blob([ab], { type: 'application/pdf' })
    } catch {
      blob = pdf.output('blob')
      if (!blob.type) blob = new Blob([blob], { type: 'application/pdf' })
    }

    if (options.returnBlobOnly) {
      return {
        ok: true,
        blob,
        method: 'blob',
        pages: pdf.getNumberOfPages(),
      }
    }

    if (handlePromise) {
      const written = await writeToSaveHandle(handlePromise, blob)
      if (written.ok || written.cancelled) {
        return {
          ...written,
          method: 'file-picker',
          pages: pdf.getNumberOfPages(),
        }
      }
    }

    try {
      pdf.save(name)
      return {
        ok: true,
        method: 'jspdf-save',
        pages: pdf.getNumberOfPages(),
      }
    } catch {
      // fall through
    }

    const viaAnchor = downloadBlob(blob, name)
    if (viaAnchor.ok) {
      return {
        ...viaAnchor,
        method: viaAnchor.method || 'anchor',
        pages: pdf.getNumberOfPages(),
      }
    }

    return { ok: false, error: 'Browser blocked the download' }
  } catch (e) {
    return { ok: false, error: e?.message || 'Form PDF generation failed' }
  }
}