/**
 * Which brand faces this build actually holds, and how to load one.
 *
 * WEIGHTS is deliberately separate from LOADERS: the book has to decide
 * whether it can honestly show a face BEFORE paying to import ~15 KB of
 * base64, and a promise it then fails to keep would put the wrong letterforms
 * on the page. One static object answers "do we have this?"; the loaders are
 * per-family dynamic imports so a book that sets two faces downloads two
 * faces, not twenty.
 *
 * Generated by scripts/build-brand-fonts.mjs; do not hand-edit.
 */

/** Family id -> the weights held, ascending. */
export const BRAND_FONT_WEIGHTS = Object.freeze({
  "fraunces": Object.freeze([400, 500, 600, 700]),
  "playfair": Object.freeze([400, 500, 600, 700]),
  "space-grotesk": Object.freeze([400, 500, 600, 700]),
  "bricolage": Object.freeze([400, 500, 600, 700]),
  "inter": Object.freeze([400, 500, 600, 700]),
  "source-serif": Object.freeze([400, 500, 600, 700]),
  "plex-mono": Object.freeze([400, 500, 600, 700]),
  "archivo": Object.freeze([400, 500, 600, 700]),
  "oswald": Object.freeze([400, 500, 600, 700]),
  "instrument-serif": Object.freeze([400]),
  "newsreader": Object.freeze([400, 500, 600, 700]),
  "eb-garamond": Object.freeze([400, 500, 600, 700]),
  "zilla-slab": Object.freeze([400, 500, 600, 700]),
  "syne": Object.freeze([400, 500, 600, 700]),
  "outfit": Object.freeze([400, 500, 600, 700]),
  "jakarta": Object.freeze([400, 500, 600, 700]),
  "libre-baskerville": Object.freeze([400, 500, 600, 700]),
  "source-sans": Object.freeze([400, 500, 600, 700]),
  "dm-sans": Object.freeze([400, 500, 600, 700]),
  "lato": Object.freeze([400, 500, 600, 700]),
})

/** Family id -> () => Promise<{ w400?, w500?, w600?, w700? }>. */
export const BRAND_FONT_LOADERS = Object.freeze({
  "fraunces": () => import('./fraunces.js'),
  "playfair": () => import('./playfair.js'),
  "space-grotesk": () => import('./space-grotesk.js'),
  "bricolage": () => import('./bricolage.js'),
  "inter": () => import('./inter.js'),
  "source-serif": () => import('./source-serif.js'),
  "plex-mono": () => import('./plex-mono.js'),
  "archivo": () => import('./archivo.js'),
  "oswald": () => import('./oswald.js'),
  "instrument-serif": () => import('./instrument-serif.js'),
  "newsreader": () => import('./newsreader.js'),
  "eb-garamond": () => import('./eb-garamond.js'),
  "zilla-slab": () => import('./zilla-slab.js'),
  "syne": () => import('./syne.js'),
  "outfit": () => import('./outfit.js'),
  "jakarta": () => import('./jakarta.js'),
  "libre-baskerville": () => import('./libre-baskerville.js'),
  "source-sans": () => import('./source-sans.js'),
  "dm-sans": () => import('./dm-sans.js'),
  "lato": () => import('./lato.js'),
})
