import { describe, expect, it } from 'vitest'
import { buildBrandPackSnapshot, downloadBrandPackVectorPdf } from './exportFiles'
import { resolvedPageBackgrounds } from './bookBuilder'

/**
 * The page-background control must reach the delivered file.
 *
 * It did not. The builder stored a page background and resolved it privately
 * inside the view, so the book on screen repainted and the exported PDF
 * ignored it entirely — a control that appears to style the deliverable and
 * does not. That is the same defect as a panel bound to a field nothing
 * writes, pointing the other way, and it is the one the owner's build rule
 * exists to stop.
 *
 * Asserted on real generated bytes rather than on the setting being stored,
 * because "the value is saved" was already true while the file ignored it.
 */

const projectWith = (pageTypeToken) => ({
  name: 'Harbor & Hearth',
  palette: ['#1C1917', '#0F766E', '#A8A29E'],
  paletteTokens: [
    { id: 't1', name: 'Ink' },
    { id: 't2', name: 'Teal' },
    { id: 't3', name: 'Stone' },
  ],
  bookBuilder: { pageBg: { pageCover: 'white', pageColors: 'white', pageType: pageTypeToken, pageBack: 'white' } },
  logoWordmark: 'Harbor & Hearth',
  detective: { story: 'Born in a shed.' },
})

const pdfBytes = async (project) => {
  const pack = buildBrandPackSnapshot({ project, tasks: [], moodItems: [] })
  const res = await downloadBrandPackVectorPdf(pack, null, { returnBlobOnly: true })
  expect(res.ok).toBe(true)
  return new Uint8Array(await res.blob.arrayBuffer())
}

describe('page background reaches the PDF', () => {
  it('resolves a token id to its hex', () => {
    const bg = resolvedPageBackgrounds(projectWith('t2'))
    expect(bg.pageType).toBe('#0F766E')
    expect(bg.pageCover).toBe('#ffffff')
  })

  it('falls back to paper when nothing is chosen', () => {
    /* A project that never opened the builder still gets its defaults, so
       the resolver always answers with paper rather than nothing — the
       generator must never receive undefined and fall through to a colour the
       screen is not showing. */
    expect(resolvedPageBackgrounds({}).pageType).toBe('#ffffff')
    expect(resolvedPageBackgrounds(projectWith('white')).pageType).toBe('#ffffff')
  })

  it('changes the generated file when the page colour changes', async () => {
    /* Two packs identical but for the page background. If the setting never
       reached the generator these would be byte-identical, which is exactly
       what was happening. */
    const [a, b] = [await pdfBytes(projectWith('white')), await pdfBytes(projectWith('t2'))]
    expect(a.length).toBeGreaterThan(1000)
    const same = a.length === b.length && a.every((v, i) => v === b[i])
    expect(same, 'the PDF ignored the chosen page colour').toBe(false)
  }, 60_000)
})
